### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by setmax** [bmresearch/Solnet.Anchor#12]
I want to install the new version,
first of all, I decided to update the installed version of Solnet.Anchor.Tool, so vs code terminal stuck, I waited for a while but nothing happened.
after that, I decided to remove the installed version and install it again, so the result was the same and the terminal is stuck without any result.

**Comment by tiago18c** [comment]
I'm sorry, it seems you have some problems on your IDE/terminal/internet connection.
I just managed to reinstall everything without any issue.
![image](https://user-images.githubusercontent.com/9483051/161062987-f446f810-816e-4531-9972-c7f0e76f7e0f.png)

**Comment by setmax** [comment]
it worked, thank you
