### ISSUE TITLE
Unable to do codegen from devnet addresses

### ISSUE THREAD

**Issue by murlokito** [bmresearch/Solnet.Anchor#4]

**Comment by tiago18c** [comment]
I assume this would be for both the tool and the source generator? 

Thinking of a network switch that defaults to mainnet and accepts both dev and test net.

**Comment by tiago18c** [comment]
I also assume there is no need for custom RPC nodes?

**Comment by murlokito** [comment]
> I assume this would be for both the tool and the source generator?
> 
> Thinking of a network switch that defaults to mainnet and accepts both dev and test net.

Yes, this seems like the best option. Don't think custom could be needed since it's only used to get the IDL

**Comment by tiago18c** [comment]
I've added this to the tool. But realised that its impossible to the source generator with the current schema, and changing it is not trivial.

Would just adding this to the tool be okay?

**Comment by murlokito** [comment]
> I've added this to the tool. But realised that its impossible to the source generator with the current schema, and changing it is not trivial.
> 
> Would just adding this to the tool be okay?

Yes, for now this would suffice.

> Another possible idea: to have the tool being able to output the IDL? This would considerably speed up some code generation if you use it from the .json file after downloading it instead of from the address

This also seems like a great idea!

**Comment by tiago18c** [comment]
Closed by #7
